apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: apache
  name: apache-manager
rules:
- apiGroups: ["", "apps", "rbac.authorization.k8s.io"]
  resources: ["pods", "deployments", "services"]
  verbs: ["get"] #, "watch", "list", "create", "patch", "delete","apply"]