apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: apache-manager-rolebinding
  namespace: apache
subjects:
- kind: user
  name: apache-user
  apiGroup: ""
  namespace: apache
roleRef:
   kind: Role
   apiGroup: "rbac.authorization.k8s.io"
   name: apache-manager
  